/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import implementaciones.EstudiantesBST;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joser
 */
public class MainFrame extends javax.swing.JFrame {
    private JPanel mainContainer;
    private CardLayout cardLayout;
    
    //paneles
    private PanelRegistroEstudiante pnlRegistroEst;
    private PanelBuscarEstudiante pnlBuscarEst;
    
    private PanelAgregarCurso pnlAgregarCurso;
    private PanelEliminarCurso pnlEliminarCurso;
    private PanelListarCurso pnlListarCurso;
    
    private PanelInscribirEstudiante pnlInscribirEst;
    private PanelListarInscritos pnlListarInscritos;
    private PanelListarEspera pnlListarEspera;
    
    private PanelEnviarSolicitud pnlEnviarSolicitud;
    private PanelProcesarSolicitud pnlProcesarSolicitud;
    
    private PanelListarPromedio pnlListarPromedio;
    private PanelRotarRol pnlRotarRol;
    
    //persistencia
    public EstudiantesBST arbolEstudiantes = new EstudiantesBST();
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        //initComponents();
        iniciarComponentes();
        configurarMenu();
        setTitle("Menú de sistema");
        setSize(800, 600);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private void iniciarComponentes() {
        cardLayout = new CardLayout();
        mainContainer = new JPanel(cardLayout);
        
        pnlRegistroEst = new PanelRegistroEstudiante(this);
        pnlBuscarEst = new PanelBuscarEstudiante(this);
        
        pnlAgregarCurso = new PanelAgregarCurso();
        pnlEliminarCurso = new PanelEliminarCurso();
        pnlListarCurso = new PanelListarCurso();
        
        pnlInscribirEst = new PanelInscribirEstudiante();
        pnlListarInscritos = new PanelListarInscritos();
        pnlListarEspera = new PanelListarEspera();
        
        pnlEnviarSolicitud = new PanelEnviarSolicitud();
        pnlProcesarSolicitud = new PanelProcesarSolicitud();
        
        pnlListarPromedio = new PanelListarPromedio();
        pnlRotarRol = new PanelRotarRol();

        
        mainContainer.add(pnlRegistroEst, "REGISTRAR_EST");
        mainContainer.add(pnlBuscarEst, "BUSCAR_EST");
        
        mainContainer.add(pnlAgregarCurso, "AGREGAR_CURSO");
        mainContainer.add(pnlEliminarCurso, "ELIMINAR_CURSO");
        mainContainer.add(pnlListarCurso, "LISTAR_CURSO");
        
        mainContainer.add(pnlInscribirEst, "INSCRIBIR_EST");
        mainContainer.add(pnlListarInscritos, "LISTAR_INSCRITOS");
        mainContainer.add(pnlListarEspera, "LISTAR_ESPERA");
        
        mainContainer.add(pnlEnviarSolicitud, "ENVIAR_SOLICITUD");
        mainContainer.add(pnlProcesarSolicitud, "PROCESAR_SOLICITUD");
        
        mainContainer.add(pnlListarPromedio, "LISTAR_PROMEDIO");
        mainContainer.add(pnlRotarRol, "ROTAR_ROL");

        this.add(mainContainer);
        
    }

    private void configurarMenu() {
        JMenuBar menuBar = new JMenuBar();

        //Estudiantes
        JMenu menuEstudiantes = new JMenu("Estudiantes");
        JMenuItem itemRegEst = new JMenuItem("Registrar estudiante");
        JMenuItem itemBusEst = new JMenuItem("Buscar estudiante por matrícula");
        menuEstudiantes.add(itemRegEst);
        menuEstudiantes.add(itemBusEst);
        itemRegEst.addActionListener(e -> mostrarPantalla("REGISTRAR_EST"));
        itemBusEst.addActionListener(e -> mostrarPantalla("BUSCAR_EST"));

        //Cursos
        JMenu menuCursos = new JMenu("Cursos");
        JMenuItem itemAddCur = new JMenuItem("Agregar curso");
        JMenuItem itemDelCur = new JMenuItem("Eliminar curso");
        JMenuItem itemLisCur = new JMenuItem("Listar cursos");
        menuCursos.add(itemAddCur);
        menuCursos.add(itemDelCur);
        menuCursos.add(itemLisCur);
        itemAddCur.addActionListener(e -> mostrarPantalla("AGREGAR_CURSO"));
        itemDelCur.addActionListener(e -> mostrarPantalla("ELIMINAR_CURSO"));
        itemLisCur.addActionListener(e -> mostrarPantalla("LISTAR_CURSO"));

        //Inscripciones
        JMenu menuInscripciones = new JMenu("Inscripciones");
        JMenuItem itemInsEst = new JMenuItem("Inscribir estudiante en curso");
        JMenuItem itemShowIns = new JMenuItem("Mostrar lista de inscritos");
        JMenuItem itemShowWait = new JMenuItem("Mostrar lista de espera");
        menuInscripciones.add(itemInsEst);
        menuInscripciones.add(itemShowIns);
        menuInscripciones.add(itemShowWait);
        itemInsEst.addActionListener(e -> mostrarPantalla("INSCRIBIR_EST"));
        itemShowIns.addActionListener(e -> mostrarPantalla("LISTAR_INSCRITOS"));
        itemShowWait.addActionListener(e -> mostrarPantalla("LISTAR_ESPERA"));

        //Calificaciones
        JMenu menuCalificaciones = new JMenu("Calificaciones");
        JMenuItem itemSolCal = new JMenuItem("Enviar solicitud de calificación (colas)");
        JMenuItem itemProcCal = new JMenuItem("Procesar siguiente solicitud");
        menuCalificaciones.add(itemSolCal);
        menuCalificaciones.add(itemProcCal);
        itemSolCal.addActionListener(e -> mostrarPantalla("ENVIAR_SOLICITUD"));
        itemProcCal.addActionListener(e -> mostrarPantalla("PROCESAR_SOLICITUD"));

        //Acciones
        JMenu menuAcciones = new JMenu("Acciones");
        JMenuItem itemDeshacer = new JMenuItem("Deshacer última acción");
        menuAcciones.add(itemDeshacer);
        itemDeshacer.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Deshaciendo última acción...");
        });

        //Reportes
        JMenu menuReportes = new JMenu("Reportes");
        JMenuItem itemRepProm = new JMenuItem("Listar estudiantes por promedio");
        JMenuItem itemRepRol = new JMenuItem("Rotar rol de tutor/líder");
        menuReportes.add(itemRepProm);
        menuReportes.add(itemRepRol);
        itemRepProm.addActionListener(e -> mostrarPantalla("LISTAR_PROMEDIO"));
        itemRepRol.addActionListener(e -> mostrarPantalla("ROTAR_ROL"));

        //Salir
        JMenu menuSalir = new JMenu("Salir");
        JMenuItem itemSalirReal = new JMenuItem("Cerrar Aplicación");
        itemSalirReal.addActionListener(e -> System.exit(0));
        menuSalir.add(itemSalirReal);

        menuBar.add(menuEstudiantes);
        menuBar.add(menuCursos);
        menuBar.add(menuInscripciones);
        menuBar.add(menuCalificaciones);
        menuBar.add(menuAcciones);
        menuBar.add(menuReportes);
        menuBar.add(menuSalir);

        this.setJMenuBar(menuBar);

    }
    
    public void mostrarPantalla(String nombrePantalla) {
        cardLayout.show(mainContainer, nombrePantalla);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
