/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import implementaciones.DoubleCircularLinkedList;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import objetos.Curso;
import objetos.Estudiante;

/**
 *
 * @author joser
 */
public class PanelListarEspera extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private JTextField txtClaveCursoEspera;
    private JTextArea txtAreaEspera;
    private JButton btnConsultar;

    /**
     * Creates new form PanelListarEspera
     */
    public PanelListarEspera(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lblTitulo = new JLabel("LISTA DE ESPERA POR CURSO", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 18));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        add(lblTitulo, gbc);

        gbc.gridwidth = 1;
        gbc.gridy = 1;
        gbc.gridx = 0;
        add(new JLabel("Clave del Curso:"), gbc);

        txtClaveCursoEspera = new JTextField(15);
        gbc.gridx = 1;
        add(txtClaveCursoEspera, gbc);

        btnConsultar = new JButton("Ver Lista de Espera");
        gbc.gridy = 2;
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        add(btnConsultar, gbc);

        txtAreaEspera = new JTextArea(15, 40);
        txtAreaEspera.setEditable(false);
        txtAreaEspera.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        JScrollPane scroll = new JScrollPane(txtAreaEspera);
        scroll.setBorder(BorderFactory.createTitledBorder("Orden de Prioridad"));
        
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weighty = 1.0; 
        add(scroll, gbc);

        btnConsultar.addActionListener(e -> listarEspera());
    }

    private void listarEspera() {
        String clave = txtClaveCursoEspera.getText().trim();
        
        Curso curso = mainFrame.sistemaEscolar.getCursos().buscarCurso(clave);
        
        if (clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa una clave de curso.");
            return;
        }
        
        if (curso == null) {
            JOptionPane.showMessageDialog(this, "El curso no existe.");
            return;
        }
        
        DoubleCircularLinkedList<Estudiante> listado = mainFrame.sistemaEscolar.mostrarListaEsperaCurso(clave);
        
        StringBuilder sb = new StringBuilder();
        sb.append("CURSO: ").append(curso.getNombre()).append("\n");
        sb.append("------------------------------------------------------------\n");
        sb.append(String.format("%-15s %-30s\n", "MATRÍCULA", "NOMBRE DEL ESTUDIANTE"));
        sb.append("------------------------------------------------------------\n");

//        if (listado.empty()) {
//            sb.append("\nNo hay estudiantes inscritos en este curso aún.");
//        } else {
//            for (Estudiante est : listado) {
//                sb.append(String.format("%-15s %-30s\n", est.getMatricula(), est.getNombreCompleto()));
//            }
//        }

        txtAreaEspera.setText(sb.toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
